[{
  "comments": [{
    "author": {
      "login": "jonalter"
    },
    "body": "@srowen I confirmed the test is having trouble with `logInfo` here and works fine with `println`. Should I just revert this?\n",
    "commit": "ccd44cc3b97e88a6296de899784d8f1c34d8d9c2",
    "createdAt": "2015-07-08T16:50:45Z",
    "diffHunk": "@@ -130,7 +131,7 @@ class ThreadingSuite extends SparkFunSuite with LocalSparkContext {\n               Thread.sleep(100)\n             }\n             if (running.get() != 4) {\n-              println(\"Waited 1 second without seeing runningThreads = 4 (it was \" +\n+              logInfo(\"Waited 1 second without seeing runningThreads = 4 (it was \" +"
  }, {
    "author": {
      "login": "srowen"
    },
    "body": "Oh darn, maybe the logging ends up dragging in some reference to the outer class. Maybe just zap this whole clause, or make the error message a field in this `ThreadingSuiteState` and use it below.\n",
    "commit": "ccd44cc3b97e88a6296de899784d8f1c34d8d9c2",
    "createdAt": "2015-07-08T16:58:16Z",
    "diffHunk": "@@ -130,7 +131,7 @@ class ThreadingSuite extends SparkFunSuite with LocalSparkContext {\n               Thread.sleep(100)\n             }\n             if (running.get() != 4) {\n-              println(\"Waited 1 second without seeing runningThreads = 4 (it was \" +\n+              logInfo(\"Waited 1 second without seeing runningThreads = 4 (it was \" +"
  }],
  "prId": 7093
}]