[
  {
    "id" : "9c37be70-61f7-4ccc-ad0b-d6b67492aaab",
    "prId" : 1523,
    "comments" : [
      {
        "id" : "c2c94dbd-8c48-44a9-8891-25b8d6e684ef",
        "parentId" : null,
        "author" : {
          "login" : "tgodzik",
          "name" : null,
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/3807253?u=094831e6a696f583ddfd86d3e5923fd8545c543a&v=4"
        },
        "body" : "In this and above the difference was actually only the parameter order, which is different when run with Scala 2.13 and 2.12. Probably due to reimplementation of standard collections. The tests now show what will really be in Metals, which is run in 2.12.",
        "createdAt" : "2020-03-25T17:30:19Z",
        "updatedAt" : "2020-04-15T13:50:25Z",
        "lastEditedBy" : {
          "login" : "tgodzik",
          "name" : null,
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/3807253?u=094831e6a696f583ddfd86d3e5923fd8545c543a&v=4"
        },
        "tags" : [
          {
            "value" : "outdated"
          }
        ]
      }
    ],
    "commit" : "1142490703f832961ac0df1debd14b4f3b12ce7d",
    "line" : null,
    "diffHunk" : "@@ -537,25 +536,7 @@ class CompletionDocSuite extends BaseCompletionSuite {\n        |- `fin`: Finally logic which if defined will be invoked after catch logic\n        |Catch - scala.util.control.Exception\n        |\"\"\".stripMargin,\n-    includeDocs = true,\n-    compat = Map(\n-      \"2.13\" ->\n-        \"\"\"|> A container class for catch/finally logic.\n-           |\n-           | Pass a different value for rethrow if you want to probably\n-           | unwisely allow catching control exceptions and other throwables\n-           | which the rest of the world may expect to get through.\n-           |\n-           |**Type Parameters**\n-           |- `T`: result type of bodies used in try and catch blocks\n-           |\n-           |**Parameters**\n-           |- `fin`: Finally logic which if defined will be invoked after catch logic"
  }
]