[{
  "comments": [{
    "author": {
      "login": "felixcheung"
    },
    "body": "is it worthwhile to do tryCatch and in the error handler, print the error?\n",
    "commit": "fc4ffc12e56b98ae2a56d3a4631797030eacc0ea",
    "createdAt": "2016-06-30T08:11:28Z",
    "diffHunk": "@@ -44,7 +44,7 @@ while (TRUE) {\n     if (inherits(p, \"masterProcess\")) {\n       close(inputCon)\n       Sys.setenv(SPARKR_WORKER_PORT = port)\n-      source(script)\n+      try(source(script))",
    "line": 5
  }, {
    "author": {
      "login": "sun-rui"
    },
    "body": "error still to stderr with try()\n",
    "commit": "fc4ffc12e56b98ae2a56d3a4631797030eacc0ea",
    "createdAt": "2016-06-30T08:14:34Z",
    "diffHunk": "@@ -44,7 +44,7 @@ while (TRUE) {\n     if (inherits(p, \"masterProcess\")) {\n       close(inputCon)\n       Sys.setenv(SPARKR_WORKER_PORT = port)\n-      source(script)\n+      try(source(script))",
    "line": 5
  }],
  "prId": 13975
}]