[{
  "comments": [{
    "author": {
      "login": "srowen"
    },
    "body": "Why not just catch NullPointerException and ignore it?\r\nBut, maybe createClient should throw a better exception to begin with?",
    "commit": "8fa404c2b694be3742a152dd57ea99430e758f0a",
    "createdAt": "2019-09-17T13:45:19Z",
    "diffHunk": "@@ -217,4 +217,16 @@ public String get(String name) {\n       assertFalse(c1.isActive());\n     }\n   }\n+\n+  @Test\n+  public void closeFactoryBeforeCreateClient() {\n+    TransportClientFactory factory = context.createClientFactory();\n+    factory.close();\n+    try {\n+      // NullPointerException occurred if factory.createClient() after factory.close()\n+      factory.createClient(TestUtils.getLocalHost(), server1.getPort());\n+    } catch (Exception e) {"
  }, {
    "author": {
      "login": "colinmjj"
    },
    "body": "The test shows exception is occurred if TransportClientFactory.createClient() called after TransportClientFactory.close().\r\nAgree to throw a better exception and the patch is updated. There should be an IOException now.",
    "commit": "8fa404c2b694be3742a152dd57ea99430e758f0a",
    "createdAt": "2019-09-18T13:43:51Z",
    "diffHunk": "@@ -217,4 +217,16 @@ public String get(String name) {\n       assertFalse(c1.isActive());\n     }\n   }\n+\n+  @Test\n+  public void closeFactoryBeforeCreateClient() {\n+    TransportClientFactory factory = context.createClientFactory();\n+    factory.close();\n+    try {\n+      // NullPointerException occurred if factory.createClient() after factory.close()\n+      factory.createClient(TestUtils.getLocalHost(), server1.getPort());\n+    } catch (Exception e) {"
  }],
  "prId": 25759
}]