[{
  "comments": [{
    "author": {
      "login": "dilipbiswal"
    },
    "body": "@kiszk Can sc.stop throw an exception ? If so, shouldn't we attempt to do a teardown first before calling super.afterAll() ?",
    "commit": "53d1ba258c62541cfe742d53c382453ae8bf1cb9",
    "createdAt": "2018-09-07T17:33:07Z",
    "diffHunk": "@@ -35,20 +35,25 @@ class KafkaRDDSuite extends SparkFunSuite with BeforeAndAfterAll {\n   private var sc: SparkContext = _\n \n   override def beforeAll {\n+    super.beforeAll()\n     sc = new SparkContext(sparkConf)\n     kafkaTestUtils = new KafkaTestUtils\n     kafkaTestUtils.setup()\n   }\n \n   override def afterAll {\n-    if (sc != null) {\n-      sc.stop\n-      sc = null\n-    }\n+    try {\n+      if (sc != null) {\n+        sc.stop\n+        sc = null\n+      }\n \n-    if (kafkaTestUtils != null) {\n-      kafkaTestUtils.teardown()\n-      kafkaTestUtils = null\n+      if (kafkaTestUtils != null) {\n+        kafkaTestUtils.teardown()\n+        kafkaTestUtils = null\n+      }\n+    } finally {\n+      super.afterAll()"
  }],
  "prId": 22337
}]