[{
  "comments": [{
    "author": {
      "login": "cloud-fan"
    },
    "body": "the `Reasons: ${e.getMessage}` is duplicated, the stack trace will include the `cause` exception.",
    "commit": "76107cb46425f4fc94800e20eeed6a2119f703d6",
    "createdAt": "2017-06-05T03:06:00Z",
    "diffHunk": "@@ -65,7 +66,8 @@ class FailureSafeParser[IN](\n         case DropMalformedMode =>\n           Iterator.empty\n         case FailFastMode =>\n-          throw e.cause\n+          throw new SparkException(\"Malformed records are detected in record parsing. \" +\n+            s\"Parse Mode: ${FailFastMode.name}. Reasons: ${e.getMessage}\", e.cause)"
  }],
  "prId": 18196
}]