[{
  "comments": [{
    "author": {
      "login": "rxin"
    },
    "body": "this was a no-op before since fs.delete can only throw IOException.\n",
    "commit": "ed7766f526e82ce37099340952c9c5ce7c32478f",
    "createdAt": "2016-03-25T06:14:29Z",
    "diffHunk": "@@ -88,11 +88,9 @@ private[sql] case class InsertIntoHadoopFsRelation(\n       case (SaveMode.ErrorIfExists, true) =>\n         throw new AnalysisException(s\"path $qualifiedOutputPath already exists.\")\n       case (SaveMode.Overwrite, true) =>\n-        Utils.tryOrIOException {",
    "line": 4
  }],
  "prId": 11951
}]