[{
  "comments": [{
    "author": {
      "login": "vanzin"
    },
    "body": "Since #10881 is already handling the one case where we don't care about the exception, can you remove this `try..catch` and just let any other exceptions propagate up the stack?\n",
    "commit": "424682e3fb0968aaa6aa02537ba22a49d7909afe",
    "createdAt": "2016-01-26T21:53:23Z",
    "diffHunk": "@@ -182,7 +182,11 @@ private[netty] class NettyRpcEnv(\n     val remoteAddr = message.receiver.address\n     if (remoteAddr == address) {\n       // Message to a local RPC endpoint.\n-      dispatcher.postOneWayMessage(message)\n+      try {\n+        dispatcher.postOneWayMessage(message)\n+      } catch {\n+        case NonFatal(e) => logWarning(e.getMessage, e)"
  }, {
    "author": {
      "login": "zsxwing"
    },
    "body": "Removed\n",
    "commit": "424682e3fb0968aaa6aa02537ba22a49d7909afe",
    "createdAt": "2016-01-26T22:06:52Z",
    "diffHunk": "@@ -182,7 +182,11 @@ private[netty] class NettyRpcEnv(\n     val remoteAddr = message.receiver.address\n     if (remoteAddr == address) {\n       // Message to a local RPC endpoint.\n-      dispatcher.postOneWayMessage(message)\n+      try {\n+        dispatcher.postOneWayMessage(message)\n+      } catch {\n+        case NonFatal(e) => logWarning(e.getMessage, e)"
  }],
  "prId": 10568
}]